apiVersion: v1
kind: Pod
metadata:
  name: nginx-shareprocess-namespace
spec:
  #shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx:1.7.9
  - name: shell
    image: busybox
    stdin: true
    tty: true
