apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  labels:
    app: data-consul-0
  name: data-consul-0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/consul/consul_0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  labels:
    app: data-consul-1
  name: data-consul-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/consul/consul_1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  labels:
    app: data-consul-2
  name: data-consul-2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/consul/consul_2
