apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 2
  selector:
    app: nginx-x
  template:
    metadata:
      labels:
        app: nginx-x
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
